name: spotifymusic_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_stripe: ^11.4.0
  url_launcher: ^6.3.0
  google_sign_in: ^5.4.1
  image_picker: ^1.1.2
  crypto: ^3.0.2
  flutter_svg:
  flutter_bloc:
  hydrated_bloc:
  path_provider:
  firebase_core:
  firebase_storage: ^12.0.0
  flutter_pdfview: ^1.4.3
  firebase_auth:
  flutter_tts: ^3.6.3
  get_it:
  dartz:
  http: ^1.2.2
  cloud_firestore:
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  firebase_app_check: ^0.3.2+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'image/logo/logo.png' # <--- cambia esta ruta si usas otro nombre

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - assets/icons/google.png
    - assets/icons/apple.png
    - assets/images/sllider.png
    - assets/images/sllider1.png
    - assets/images/sllider2.png
    - assets/images/sllider3.png

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
